name = "256t-org-site"
main = "worker.js"
compatibility_date = "2024-01-01"

# Route all 256t.org traffic through this worker
routes = [
  { pattern = "256t.org", zone_name = "256t.org" },
  { pattern = "256t.org/*", zone_name = "256t.org" },
  { pattern = "www.256t.org", zone_name = "256t.org" },
  { pattern = "www.256t.org/*", zone_name = "256t.org" }
]

# Bind the R2 bucket to the worker
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "256t-cids"
